# Generated by Django 5.0.6 on 2025-02-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeflow', '0003_account_alter_order_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('minimum_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regulation', models.CharField(max_length=100)),
                ('account_types', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
