# Generated by Django 5.0.6 on 2025-02-02 23:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeflow', '0004_broker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_withdrawals',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='high_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='low_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='volume',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='security_key',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='trade',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tradeflow.broker'),
        ),
        migrations.AddField(
            model_name='trade',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tradeflow_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
