# Generated by Django 6.0.4 on 2026-04-11 15:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tradeflow",
            "0005_account_total_withdrawals_account_withdrawal_limit_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crypto_type",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("BTC", "Bitcoin"),
                            ("ETH", "Ethereum"),
                            ("BNB", "Binance Coin"),
                            ("TRX", "TRON"),
                            ("EOS", "EOS"),
                            ("XMR", "Monero"),
                            ("KCS", "KuCoin Token"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "total_balance",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("wallet_address", models.CharField(blank=True, max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_balances",
                        to="tradeflow.account",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Crypto Balances",
                "unique_together": {("account", "crypto_type")},
            },
        ),
    ]
