# Generated by Django 6.0.4 on 2026-04-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeflow', '0006_cryptobalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptobalance',
            name='crypto_type',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('BNB', 'Binance Coin'), ('USDT', 'Tether'), ('SOL', 'Solana'), ('XRP', 'XRP'), ('USDC', 'USD Coin')], max_length=10),
        ),
    ]
